version: 2.1

orbs:
  docker: arribada/docker@0.0.12
workflows:
  publish:
    jobs:
      - docker/publish:
          containerName: lora-app-server
          context: org-context
          filters:
            branches:
                only: 
                  - master
            #   ignore: /.*/
            # tags:
            #   only: /v\d+\.\d+\.\d+$/
